content/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from content import views


urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.loginUser, name='loginUser'),
    path('register', views.RegisterUser, name='registerUser'),
    path('logout', views.logoutUser, name='logoutUser'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldremo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('content.urls')),
    path('admin/', admin.site.urls),
]

content/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    post = models.TextField()

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

content/forms.py
import re
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)

class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = [
            'username',
            'password'
        ]

class PostForm(forms.Form):
    post = forms.CharField(required=True)
    image = forms.ImageField(required=True)

content/views.py
from tkinter import Image
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import *

from content.forms import LoginForm, PostForm, RegisterForm
from content.models import Post

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect('loginUser')
    else:
        posts = Post.objects.order_by('-id')
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.cleaned_data['post']
                image = request.FILES.getlist('image')

                new_post = Post(post=post)
                new_post.save()
                for imageitem in image:
                    new_image = Image(post=new_post, image=imageitem)
                    new_image.save()
        else:
            form = PostForm()
        context = {
            'form': form,
            'posts': posts
        }
        return render(request, 'index.html', context)
    
def loginUser(request):
    if request.user.is_authenticated:
        return redirect('index')
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                form.add_error('username', 'Invalid username or password.')
    else:
        form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'login.html', context)

def RegisterUser(request):
    if request.user.is_authenticated:
        return redirect('index')
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            new_user = User.objects.create_user(username, email, password)
            new_user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                form.add_error('username', 'Error while registering.')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, 'register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('loginUser')

content/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WORLDREMO</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="./">HOME</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="./logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="./login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="./register">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

content/templates/index.html
{% extends "base.html" %}

{% block content %}
<form method="post" , enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="image" class="form-label">Image</label>
        <input type="file" name="image" id="image" class="form-control" accept=".jpg, .jpeg, .png" multiple>
        {% for error in form.errors.image %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label for="post" class="form-label">Post</label>
        <textarea name="post" id="post" rows="5" class="form-control"></textarea>
        {% for error in form.errors.post %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
<hr>
{% for post in posts %}
<div class="post">
    <div class="mb-3">
        <b>{{ post.post }}</b>
    </div>
    <div id="carouselExample" class="carousel slide bg-dark">
        <div class="carousel-inner">
            {% for image in post.image_set.all %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ image.image.url }}" class="d-block" alt="{{ image.image }}">
            </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
{% endfor %}
{% endblock %}

content/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" name="username" id="username" class="form-control">
        {% for error in form.errors.username %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" name="password" id="password" class="form-control">
        {% for error in form.errors.password %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

content/templates/register.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" name="username" id="username" class="form-control">
        {% for error in form.errors.username %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="text" name="email" id="email" class="form-control">
        {% for error in form.errors.email %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" name="password" id="password" class="form-control">
        {% for error in form.errors.password %}
        <b class="text-danger">{{ error }}</b>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}